apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Jeus8(Openjdk1.7) Default Template
    name: Jeus8-Default Template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    template:
      metadata:
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
          - name: ${APPLICATION_NAME}
            image: docker-registry.default.svc:5000/${CICD_NAME}/${IMAGE_NAME}
            ports:
              - containerPort: ${TARGET_PORT}
                protocol: TCP
        restartPolicy: Always
        serviceAccountName: tmax
        serviceAccount: tmax
    replicas: 1
    triggers:
      - type: ImageChange
        imageChangeParams:
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            namespace: ${CICD_NAME}
            name: ${IMAGE_NAME}:latest
    strategy:
      type: Recreate
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
      - name: ${PORT}-${TARGET_PORT}
        protocol: TCP
        port: ${{PORT}}
        targetPort: ${{TARGET_PORT}}
    selector:
      name: ${APPLICATION_NAME}
    type: ClusterIP
parameters:
- description: Image Name
  name: IMAGE_NAME
- description: Application Name
  name: APPLICATION_NAME
- description: CICD Name
  name: CICD_NAME
- description: Port
  name: PORT
- description: Target Port
  name: TARGET_PORT